spring:
  application:
    name: sentinel-demo
  cloud:
    sentinel:
      transport:
#        port: 8719
#        dashboard: 127.0.0.1:8080
        port: 8720
        dashboard: 192.168.1.247:8084

server:
  port: 8079

eurekaServer:
  host: localhost
  port: 8761
  user: root
  password: root

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka

#csp:
#  sentinel:
#    dashboard:
#      server: 127.0.0.1:18080

# -Dcsp.sentinel.dashboard.server=localhost:8080
