version: '3'
services:
  eureka-server1:
    image: hv/cloud-demo-eureka
    container_name: eureka-server1
    restart: always
    ports:
      - 8761:8761
    environment:
      - spring.profiles.active=prod
      - eureka.client.service-url.defaultZone=http://root:root@eureka-server2:8761/eureka/,http://root:root@eureka-server3:8761/eureka/
  eureka-server2:
    image: hv/cloud-demo-eureka
    container_name: eureka-server2
    restart: always
    ports:
      - 8762:8761
    environment:
      - spring.profiles.active=prod
      - eureka.client.service-url.defaultZone=http://root:root@eureka-server1:8761/eureka/,http://root:root@eureka-server3:8761/eureka/
  eureka-server3:
    image: hv/cloud-demo-eureka
    container_name: eureka-server3
    restart: always
    ports:
      - 8763:8761
    environment:
      - spring.profiles.active=prod
      - eureka.client.service-url.defaultZone=http://root:root@eureka-server2:8761/eureka/,http://root:root@eureka-server1:8761/eureka/



  cloud-demo-provider:
    image: hv/cloud-demo-provider
    container_name: cloud-demo-provider
    restart: always
    ports:
      - 8078:8078
    environment:
      - spring.profiles.active=prod
      - eureka.client.service-url.defaultZone=http://root:root@eureka-server1:8761/eureka/,http://root:root@eureka-server2:8761/eureka/,http://root:root@eureka-server3:8761/eureka/
    depends_on:
      - "eureka-server1"
      - "eureka-server2"
      - "eureka-server3"

  cloud-demo-consumer-feign:
    container_name: cloud-demo-consumer-feign
    image: hv/cloud-demo-consumer-feign
    restart: always
    ports:
      - 8089:8089
    environment:
      - spring.profiles.active=prod
      - eureka.client.service-url.defaultZone=http://root:root@eureka-server1:8761/eureka/,http://root:root@eureka-server2:8761/eureka/,http://root:root@eureka-server3:8761/eureka/
    depends_on:
      - "eureka-server1"
      - "eureka-server2"
      - "eureka-server3"
